name: image_editor_plus
description: Image Editor Plugin with filters, drawing, text and emoji like stories.
version: 0.2.0
homepage: https://ensorta.com
repository: https://github.com/hsbijarniya/image_editor_plus

environment:
    sdk: ">=2.15.1 <4.0.0"
    flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.1.0
  image_picker: ^1.0.2
  screenshot: ^3.0.0
  flutter_colorpicker: ^1.0.3
  extended_image: ^8.0.2
  image: ^4.0.15
  image_editor: ^1.0.2
  colorfilter_generator: ^0.0.8
  hand_signature: ^3.0.0
  flutter_image_compress: ^2.0.4
  
  image_painter:
    git:
      url: https://github.com/fodilfliti/yellowQ-Flutter-Image-Painter.git
      ref: b90f86deb8c149ed9c15d10ba22c397c4944aa55
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
    uses-material-design: true
